name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #windows-latest, ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install Dependencies
        run: npm --prefix ./core install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm --prefix ./core run build:linux

      - name: build-mac
        env:
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
        if: matrix.os == 'macos-latest'
        run: npm --prefix ./core run build:mac

      # - name: build-win
      #   if: matrix.os == 'windows-latest'
      #   run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            core/dist/*.exe
            core/dist/*.zip
            core/dist/*.dmg
            core/dist/*.AppImage
            core/dist/*.snap
            core/dist/*.deb
            core/dist/*.rpm
            core/dist/*.tar.gz
            core/dist/*.yml
            core/dist/*.blockmap
